services:
  shards3:
    build:
      context: ..
      dockerfile: container/Containerfile.shards3
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./testDir:/app/data
      - ../shards3/backends.yaml:/app/data/backends.yaml
    working_dir: /app/data

#volumes:
#  shards3_data:
